require("user.options")
require("user.keymaps")
require("user.autocmds")
require("user.commands")
local spec = require("user.spec")
-- plugins
spec.add(require("user.colorscheme"))
spec.add(require("user.devicons"))
spec.add(require("user.virt-column"))
spec.add(require("user.treesitter"))
spec.add(require("user.comment"))
spec.add(require("user.mason"))
spec.add(require("user.schemastore"))
spec.add(require("user.lspconfig"))
-- spec.add(require"user.null-ls")
spec.add(require("user.conform"))
spec.add(require("user.nvim-lint"))
spec.add(require("user.fzf-lua"))
spec.add(require("user.nvimtree"))
spec.add(require("user.oil"))
spec.add(require("user.lualine"))
spec.add(require("user.cmp"))
spec.add(require("user.luasnip"))
spec.add(require("user.undotree"))
spec.add(require("user.fugitive"))
spec.add(require("user.gitsigns"))
spec.add(require("user.aerial"))
spec.add(require("user.emmet"))
spec.add(require("user.navigator"))
-- spec.add(require"user.autopairs")
-- extras
spec.add(require("user.extras.matchup"))
spec.add(require("user.extras.rainbow"))
spec.add(require("user.extras.copilot"))
-- spec.add(require"user.extras.supermaven")
spec.add(require("user.extras.toggleterm"))
spec.add(require("user.extras.rest"))
spec.add(require("user.extras.dressing"))
spec.add(require("user.extras.trouble"))
spec.add(require("user.extras.vim-visual-multi"))
spec.add(require("user.extras.dadbod"))
spec.add(require("user.extras.surround"))
spec.add(require("user.extras.dap"))
-- spec.add(require"user.extras.twoslash")
-- spec.add(require"user.extras.copilotChat")
-- spec.add(require"user.extras.chatgpt")
-- spec.add(require"user.extras.avante")
-- spec.add(require"user.extras.aider")
spec.add(require("user.extras.codecompanion"))
spec.add(require("user.extras.render-markdown"))
spec.add(require("user.extras.obsidian"))
-- spec.add(require("user.extras.which-key"))
require("user.lazy")
